"""FlashAlpha Python SDK — options exposure analytics API."""

from .client import FlashAlpha
from .exceptions import (
    AuthenticationError,
    FlashAlphaError,
    NotFoundError,
    RateLimitError,
    ServerError,
    TierRestrictedError,
)
from .types import (
    ExposureSummaryExposures,
    ExposureSummaryHedgingEstimate,
    ExposureSummaryHedgingMove,
    ExposureSummaryInterpretation,
    ExposureSummaryResponse,
    ExposureSummaryZeroDte,
    FlowAdjustedDealerRisk,
    FlowCumulativePoint,
    FlowDealerRiskResponse,
    FlowDexResponse,
    FlowGexResponse,
    FlowLevelsResponse,
    FlowLiveResponse,
    FlowOiResponse,
    FlowOptionBlock,
    FlowOptionBlocksResponse,
    FlowOptionCumulativeResponse,
    FlowOptionHistoryBucket,
    FlowOptionHistoryResponse,
    FlowOptionLeaderRow,
    FlowOptionLeaderboardResponse,
    FlowOptionOutliersResponse,
    FlowOptionRecentResponse,
    FlowOptionSummaryResponse,
    FlowOptionTrade,
    FlowOutlierRow,
    FlowPinRiskBreakdown,
    FlowPinRiskResponse,
    FlowSignal,
    FlowSignalEnrichment,
    FlowSignalScoreBreakdown,
    FlowSignalsChain,
    FlowSignalsResponse,
    FlowSignalsSummaryResponse,
    FlowStockBlock,
    FlowStockBlocksResponse,
    FlowStockCumulativeResponse,
    FlowStockHistoryBucket,
    FlowStockHistoryResponse,
    FlowStockLeaderRow,
    FlowStockLeaderboardResponse,
    FlowStockOutliersResponse,
    FlowStockRecentResponse,
    FlowStockSummaryResponse,
    FlowStockTrade,
    FlowSummaryResponse,
    VrpCore,
    VrpDirectional,
    VrpGexConditioned,
    VrpMacro,
    VrpRegime,
    VrpResponse,
    VrpStrategyScores,
    VrpTermItem,
    VrpVannaConditioned,
    MaxPainResponse,
    MaxPainDistance,
    MaxPainCurveRow,
    MaxPainOiRow,
    MaxPainByExpirationRow,
    MaxPainDealerAlignment,
    MaxPainExpectedMove,
    ZeroDteDecay,
    ZeroDteExpectedMove,
    ZeroDteExposures,
    ZeroDteFlow,
    ZeroDteHedging,
    ZeroDteHedgingBucket,
    ZeroDteLevels,
    ZeroDteLiquidity,
    ZeroDteMetadata,
    ZeroDtePinComponents,
    ZeroDtePinRisk,
    ZeroDteRegime,
    ZeroDteResponse,
    ZeroDteStrike,
    ZeroDteVolContext,
    # ── StockSummary ──
    StockSummaryPrice,
    StockSummarySkew25d,
    StockSummaryIvTermItem,
    StockSummaryVolatility,
    StockSummaryOptionsFlow,
    StockSummaryInterpretation,
    StockSummaryHedgingMove,
    StockSummaryHedgingEstimate,
    StockSummaryZeroDte,
    StockSummaryTopStrike,
    StockSummaryExposure,
    StockSummaryMacroIndex,
    StockSummaryVixTermLevels,
    StockSummaryVixTermStructure,
    StockSummaryVixFutures,
    StockSummaryFearAndGreed,
    StockSummaryMacro,
    StockSummaryResponse,
    # ── Narrative ──
    NarrativeOiChange,
    NarrativeData,
    Narrative,
    NarrativeResponse,
    # ── ExposureLevels ──
    ExposureLevels,
    ExposureLevelsResponse,
    # ── PricingGreeks ──
    PricingInputs,
    PricingFirstOrder,
    PricingSecondOrder,
    PricingThirdOrder,
    PricingAdditional,
    PricingGreeksResponse,
    # ── Volatility ──
    VolatilityRealizedVol,
    VolatilityIvRvSpreads,
    VolatilitySkewProfile,
    VolatilityTermStructure,
    VolatilityIvDispersion,
    VolatilityGexByDte,
    VolatilityThetaByDte,
    VolatilityPcByExpiry,
    VolatilityPcByMoneyness,
    VolatilityPutCallProfile,
    VolatilityOiConcentration,
    VolatilityHedgingScenario,
    VolatilityLiquidity,
    VolatilityResponse,
    # ── AdvVolatility ──
    AdvVolSviParam,
    AdvVolForwardPrice,
    AdvVolTotalVarianceSurface,
    AdvVolArbitrageFlag,
    AdvVolVarianceSwap,
    AdvVolGreekSurface,
    AdvVolGreeksSurfaces,
    AdvVolatilityResponse,
    # ── Surface ──
    SurfaceResponse,
    # ── Per-strike Exposure (GEX/DEX/VEX/CHEX) ──
    GexStrikeRow,
    GexResponse,
    DexStrikeRow,
    DexResponse,
    VexStrikeRow,
    VexResponse,
    ChexStrikeRow,
    ChexResponse,
    # ── Live-only Quote endpoints ──
    OptionQuoteResponse,
    StockQuoteResponse,
    # ── Pricing IV ──
    PricingIvInputs,
    PricingIvResponse,
    # ── Pricing Kelly ──
    PricingKellyInputs,
    PricingKellySizing,
    PricingKellyAnalysis,
    PricingKellyResponse,
    # ── Account / Reference / System ──
    AccountResponse,
    TickersResponse,
    SymbolsResponse,
    OptionsMetaExpiration,
    OptionsMetaResponse,
    HealthResponse,
    # ── Screener ──
    ScreenerMeta,
    ScreenerResponse,
    ScreenerField,
    ScreenerFieldsResponse,
    # ── Strategy Signals ──
    StrategyLeg,
    StrategyStructure,
    StrategyRiskFlag,
    StrategyDataQuality,
    StrategyDecisionResponse,
    # ── Earnings ──
    EarningsCalendarEvent,
    EarningsCalendarResponse,
    EarningsExpectedMoveBlock,
    EarningsExpectedMoveResponse,
    EarningsHistoryRow,
    EarningsHistoryResponse,
    EarningsIvCrushCurrent,
    EarningsIvCrushDistribution,
    EarningsIvCrushResponse,
    EarningsVrpBlock,
    EarningsSurpriseReaction,
    EarningsVrpResponse,
    EarningsDealerLevels,
    EarningsDealerGexBucket,
    EarningsDealerTopStrike,
    EarningsDealerPositioningResponse,
    EarningsStrategyScores,
    EarningsStrategyContext,
    EarningsStrategiesResponse,
    EarningsScreenerEvent,
    EarningsScreenerResponse,
    # ── Structures ──
    StructurePnlLeg,
    StructurePnlPoint,
    StructurePnlResponse,
    StructureGreeksLeg,
    StructurePositionGreeks,
    StructureGreeksResponse,
    # ── Surface SVI ──
    SurfaceSviResponse,
    # ── Expected Move ──
    ExpectedMoveItem,
    ExpectedMoveResponse,
    # ── Exposure (additional) ──
    ExposureSheetTotals,
    ExposureSheetLis,
    ExposureSheetPeak,
    ExposureSheetStrike,
    ExposureSheetResponse,
    ExposureTermDteBucket,
    ExposureTermExpiry,
    ExposureTermStructureResponse,
    ExposureBasketAggregate,
    ExposureBasketConstituent,
    ExposureBasketResponse,
    ExposureOiDiffRow,
    ExposureOiDiffResponse,
    # ── Volatility / Liquidity (additional) ──
    LiquidityExpiry,
    LiquidityResponse,
    SkewTermExpiry,
    SkewTermResponse,
    SpotVolCorrelationResponse,
    RealizedVolatilityEstimator,
    RealizedVolatilityEstimators,
    RealizedVolatilityResponse,
    VolatilityForecastEwma,
    VolatilityForecastHarComponents,
    VolatilityForecastHar,
    VolatilityForecastGarchParams,
    VolatilityForecastGarchPoint,
    VolatilityForecastGarch,
    VolatilityForecastResponse,
    DispersionContributor,
    DispersionResponse,
    # ── Macro / Universe ──
    VixStateResponse,
    UniverseSymbol,
    UniverseResponse,
    # ── Flow (additional) ──
    FlowDealerPremiumResponse,
    ZeroDteFlowDirection,
    FlowZeroDteSnapshotResponse,
    FlowZeroDteSeriesBar,
    FlowZeroDteSeriesResponse,
    FlowZeroDteHedgeFlowBar,
    FlowZeroDteHedgeFlowResponse,
    FlowZeroDteHeatmapBar,
    FlowZeroDteHeatmapResponse,
    FlowZeroDteStrikeFlowBar,
    FlowZeroDteStrikeFlowResponse,
    FlowZeroDteLeaderboardEntry,
    FlowZeroDteLeaderboardResponse,
    FlowStockBar,
    FlowStockBarsResponse,
    # ── VRP History ──
    VrpHistoryRow,
    VrpHistoryResponse,
)

__version__ = "1.1.0"
__all__ = [
    "FlashAlpha",
    "FlashAlphaError",
    "AuthenticationError",
    "TierRestrictedError",
    "NotFoundError",
    "RateLimitError",
    "ServerError",
    "ZeroDteResponse",
    "ZeroDteRegime",
    "ZeroDteExposures",
    "ZeroDteExpectedMove",
    "ZeroDtePinRisk",
    "ZeroDtePinComponents",
    "ZeroDteHedging",
    "ZeroDteHedgingBucket",
    "ZeroDteDecay",
    "ZeroDteVolContext",
    "ZeroDteFlow",
    "ZeroDteLevels",
    "ZeroDteLiquidity",
    "ZeroDteMetadata",
    "ZeroDteStrike",
    # ── ExposureSummary ──
    "ExposureSummaryResponse",
    "ExposureSummaryExposures",
    "ExposureSummaryInterpretation",
    "ExposureSummaryHedgingEstimate",
    "ExposureSummaryHedgingMove",
    "ExposureSummaryZeroDte",
    # ── VRP ──
    "VrpResponse",
    "VrpCore",
    "VrpDirectional",
    "VrpTermItem",
    "VrpGexConditioned",
    "VrpVannaConditioned",
    "VrpRegime",
    "VrpStrategyScores",
    "VrpMacro",
    # ── MaxPain ──
    "MaxPainResponse",
    "MaxPainDistance",
    "MaxPainCurveRow",
    "MaxPainOiRow",
    "MaxPainByExpirationRow",
    "MaxPainDealerAlignment",
    "MaxPainExpectedMove",
    # ── StockSummary ──
    "StockSummaryResponse",
    "StockSummaryPrice",
    "StockSummarySkew25d",
    "StockSummaryIvTermItem",
    "StockSummaryVolatility",
    "StockSummaryOptionsFlow",
    "StockSummaryInterpretation",
    "StockSummaryHedgingMove",
    "StockSummaryHedgingEstimate",
    "StockSummaryZeroDte",
    "StockSummaryTopStrike",
    "StockSummaryExposure",
    "StockSummaryMacroIndex",
    "StockSummaryVixTermLevels",
    "StockSummaryVixTermStructure",
    "StockSummaryVixFutures",
    "StockSummaryFearAndGreed",
    "StockSummaryMacro",
    # ── Narrative ──
    "NarrativeResponse",
    "Narrative",
    "NarrativeData",
    "NarrativeOiChange",
    # ── ExposureLevels ──
    "ExposureLevelsResponse",
    "ExposureLevels",
    # ── PricingGreeks ──
    "PricingGreeksResponse",
    "PricingInputs",
    "PricingFirstOrder",
    "PricingSecondOrder",
    "PricingThirdOrder",
    "PricingAdditional",
    # ── Volatility ──
    "VolatilityResponse",
    "VolatilityRealizedVol",
    "VolatilityIvRvSpreads",
    "VolatilitySkewProfile",
    "VolatilityTermStructure",
    "VolatilityIvDispersion",
    "VolatilityGexByDte",
    "VolatilityThetaByDte",
    "VolatilityPcByExpiry",
    "VolatilityPcByMoneyness",
    "VolatilityPutCallProfile",
    "VolatilityOiConcentration",
    "VolatilityHedgingScenario",
    "VolatilityLiquidity",
    # ── AdvVolatility ──
    "AdvVolatilityResponse",
    "AdvVolSviParam",
    "AdvVolForwardPrice",
    "AdvVolTotalVarianceSurface",
    "AdvVolArbitrageFlag",
    "AdvVolVarianceSwap",
    "AdvVolGreekSurface",
    "AdvVolGreeksSurfaces",
    # ── Surface ──
    "SurfaceResponse",
    # ── Per-strike Exposure (GEX/DEX/VEX/CHEX) ──
    "GexResponse",
    "GexStrikeRow",
    "DexResponse",
    "DexStrikeRow",
    "VexResponse",
    "VexStrikeRow",
    "ChexResponse",
    "ChexStrikeRow",
    # ── Live-only Quote endpoints ──
    "OptionQuoteResponse",
    "StockQuoteResponse",
    # ── Pricing IV (Free+, live-only) ──
    "PricingIvResponse",
    "PricingIvInputs",
    # ── Pricing Kelly (Growth+, live-only) ──
    "PricingKellyResponse",
    "PricingKellyInputs",
    "PricingKellySizing",
    "PricingKellyAnalysis",
    # ── Account / Reference / System ──
    "AccountResponse",
    "TickersResponse",
    "SymbolsResponse",
    "OptionsMetaResponse",
    "OptionsMetaExpiration",
    "HealthResponse",
    # ── Screener ──
    "ScreenerResponse",
    "ScreenerMeta",
    # ── Flow (live, simulation-aware) ──
    "FlowLevelsResponse",
    "FlowPinRiskResponse",
    "FlowPinRiskBreakdown",
    "FlowSummaryResponse",
    "FlowOiResponse",
    "FlowGexResponse",
    "FlowDexResponse",
    "FlowDealerRiskResponse",
    "FlowAdjustedDealerRisk",
    "FlowLiveResponse",
    "FlowOptionTrade",
    "FlowOptionRecentResponse",
    "FlowOptionSummaryResponse",
    "FlowOptionBlock",
    "FlowOptionBlocksResponse",
    "FlowOptionHistoryBucket",
    "FlowOptionHistoryResponse",
    "FlowCumulativePoint",
    "FlowOptionCumulativeResponse",
    "FlowStockTrade",
    "FlowStockRecentResponse",
    "FlowStockSummaryResponse",
    "FlowStockBlock",
    "FlowStockBlocksResponse",
    "FlowStockHistoryBucket",
    "FlowStockHistoryResponse",
    "FlowStockCumulativeResponse",
    "FlowOptionLeaderRow",
    "FlowOptionLeaderboardResponse",
    "FlowOutlierRow",
    "FlowOptionOutliersResponse",
    "FlowStockLeaderRow",
    "FlowStockLeaderboardResponse",
    "FlowStockOutliersResponse",
    "FlowSignalsChain",
    "FlowSignalScoreBreakdown",
    "FlowSignalEnrichment",
    "FlowSignal",
    "FlowSignalsResponse",
    "FlowSignalsSummaryResponse",
    # ── Screener Fields ──
    "ScreenerField",
    "ScreenerFieldsResponse",
    # ── Strategy Signals ──
    "StrategyLeg",
    "StrategyStructure",
    "StrategyRiskFlag",
    "StrategyDataQuality",
    "StrategyDecisionResponse",
    # ── Earnings ──
    "EarningsCalendarEvent",
    "EarningsCalendarResponse",
    "EarningsExpectedMoveBlock",
    "EarningsExpectedMoveResponse",
    "EarningsHistoryRow",
    "EarningsHistoryResponse",
    "EarningsIvCrushCurrent",
    "EarningsIvCrushDistribution",
    "EarningsIvCrushResponse",
    "EarningsVrpBlock",
    "EarningsSurpriseReaction",
    "EarningsVrpResponse",
    "EarningsDealerLevels",
    "EarningsDealerGexBucket",
    "EarningsDealerTopStrike",
    "EarningsDealerPositioningResponse",
    "EarningsStrategyScores",
    "EarningsStrategyContext",
    "EarningsStrategiesResponse",
    "EarningsScreenerEvent",
    "EarningsScreenerResponse",
    # ── Structures ──
    "StructurePnlLeg",
    "StructurePnlPoint",
    "StructurePnlResponse",
    "StructureGreeksLeg",
    "StructurePositionGreeks",
    "StructureGreeksResponse",
    # ── Surface SVI ──
    "SurfaceSviResponse",
    # ── Expected Move ──
    "ExpectedMoveItem",
    "ExpectedMoveResponse",
    # ── Exposure (additional) ──
    "ExposureSheetTotals",
    "ExposureSheetLis",
    "ExposureSheetPeak",
    "ExposureSheetStrike",
    "ExposureSheetResponse",
    "ExposureTermDteBucket",
    "ExposureTermExpiry",
    "ExposureTermStructureResponse",
    "ExposureBasketAggregate",
    "ExposureBasketConstituent",
    "ExposureBasketResponse",
    "ExposureOiDiffRow",
    "ExposureOiDiffResponse",
    # ── Volatility / Liquidity (additional) ──
    "LiquidityExpiry",
    "LiquidityResponse",
    "SkewTermExpiry",
    "SkewTermResponse",
    "SpotVolCorrelationResponse",
    "RealizedVolatilityEstimator",
    "RealizedVolatilityEstimators",
    "RealizedVolatilityResponse",
    "VolatilityForecastEwma",
    "VolatilityForecastHarComponents",
    "VolatilityForecastHar",
    "VolatilityForecastGarchParams",
    "VolatilityForecastGarchPoint",
    "VolatilityForecastGarch",
    "VolatilityForecastResponse",
    "DispersionContributor",
    "DispersionResponse",
    # ── Macro / Universe ──
    "VixStateResponse",
    "UniverseSymbol",
    "UniverseResponse",
    # ── Flow (additional) ──
    "FlowDealerPremiumResponse",
    "ZeroDteFlowDirection",
    "FlowZeroDteSnapshotResponse",
    "FlowZeroDteSeriesBar",
    "FlowZeroDteSeriesResponse",
    "FlowZeroDteHedgeFlowBar",
    "FlowZeroDteHedgeFlowResponse",
    "FlowZeroDteHeatmapBar",
    "FlowZeroDteHeatmapResponse",
    "FlowZeroDteStrikeFlowBar",
    "FlowZeroDteStrikeFlowResponse",
    "FlowZeroDteLeaderboardEntry",
    "FlowZeroDteLeaderboardResponse",
    "FlowStockBar",
    "FlowStockBarsResponse",
    # ── VRP History ──
    "VrpHistoryRow",
    "VrpHistoryResponse",
]
