"""FlashAlpha Python SDK — options exposure analytics API."""

from .client import FlashAlpha
from .exceptions import (
    AuthenticationError,
    FlashAlphaError,
    NotFoundError,
    RateLimitError,
    ServerError,
    TierRestrictedError,
)
from .types import (
    ExposureSummaryExposures,
    ExposureSummaryHedgingEstimate,
    ExposureSummaryHedgingMove,
    ExposureSummaryInterpretation,
    ExposureSummaryResponse,
    ExposureSummaryZeroDte,
    VrpCore,
    VrpDirectional,
    VrpGexConditioned,
    VrpMacro,
    VrpRegime,
    VrpResponse,
    VrpStrategyScores,
    VrpTermItem,
    VrpVannaConditioned,
    MaxPainResponse,
    MaxPainDistance,
    MaxPainCurveRow,
    MaxPainOiRow,
    MaxPainByExpirationRow,
    MaxPainDealerAlignment,
    MaxPainExpectedMove,
    ZeroDteDecay,
    ZeroDteExpectedMove,
    ZeroDteExposures,
    ZeroDteFlow,
    ZeroDteHedging,
    ZeroDteHedgingBucket,
    ZeroDteLevels,
    ZeroDteLiquidity,
    ZeroDteMetadata,
    ZeroDtePinComponents,
    ZeroDtePinRisk,
    ZeroDteRegime,
    ZeroDteResponse,
    ZeroDteStrike,
    ZeroDteVolContext,
    # ── StockSummary ──
    StockSummaryPrice,
    StockSummarySkew25d,
    StockSummaryIvTermItem,
    StockSummaryVolatility,
    StockSummaryOptionsFlow,
    StockSummaryInterpretation,
    StockSummaryHedgingMove,
    StockSummaryHedgingEstimate,
    StockSummaryZeroDte,
    StockSummaryTopStrike,
    StockSummaryExposure,
    StockSummaryMacroIndex,
    StockSummaryVixTermLevels,
    StockSummaryVixTermStructure,
    StockSummaryVixFutures,
    StockSummaryFearAndGreed,
    StockSummaryMacro,
    StockSummaryResponse,
    # ── Narrative ──
    NarrativeOiChange,
    NarrativeData,
    Narrative,
    NarrativeResponse,
    # ── ExposureLevels ──
    ExposureLevels,
    ExposureLevelsResponse,
    # ── PricingGreeks ──
    PricingInputs,
    PricingFirstOrder,
    PricingSecondOrder,
    PricingThirdOrder,
    PricingAdditional,
    PricingGreeksResponse,
    # ── Volatility ──
    VolatilityRealizedVol,
    VolatilityIvRvSpreads,
    VolatilitySkewProfile,
    VolatilityTermStructure,
    VolatilityIvDispersion,
    VolatilityGexByDte,
    VolatilityThetaByDte,
    VolatilityPcByExpiry,
    VolatilityPcByMoneyness,
    VolatilityPutCallProfile,
    VolatilityOiConcentration,
    VolatilityHedgingScenario,
    VolatilityLiquidity,
    VolatilityResponse,
    # ── AdvVolatility ──
    AdvVolSviParam,
    AdvVolForwardPrice,
    AdvVolTotalVarianceSurface,
    AdvVolArbitrageFlag,
    AdvVolVarianceSwap,
    AdvVolGreekSurface,
    AdvVolGreeksSurfaces,
    AdvVolatilityResponse,
    # ── Surface ──
    SurfaceResponse,
    # ── Per-strike Exposure (GEX/DEX/VEX/CHEX) ──
    GexStrikeRow,
    GexResponse,
    DexStrikeRow,
    DexResponse,
    VexStrikeRow,
    VexResponse,
    ChexStrikeRow,
    ChexResponse,
    # ── Live-only Quote endpoints ──
    OptionQuoteResponse,
    StockQuoteResponse,
)

__version__ = "0.4.0rc1"
__all__ = [
    "FlashAlpha",
    "FlashAlphaError",
    "AuthenticationError",
    "TierRestrictedError",
    "NotFoundError",
    "RateLimitError",
    "ServerError",
    "ZeroDteResponse",
    "ZeroDteRegime",
    "ZeroDteExposures",
    "ZeroDteExpectedMove",
    "ZeroDtePinRisk",
    "ZeroDtePinComponents",
    "ZeroDteHedging",
    "ZeroDteHedgingBucket",
    "ZeroDteDecay",
    "ZeroDteVolContext",
    "ZeroDteFlow",
    "ZeroDteLevels",
    "ZeroDteLiquidity",
    "ZeroDteMetadata",
    "ZeroDteStrike",
    # ── ExposureSummary ──
    "ExposureSummaryResponse",
    "ExposureSummaryExposures",
    "ExposureSummaryInterpretation",
    "ExposureSummaryHedgingEstimate",
    "ExposureSummaryHedgingMove",
    "ExposureSummaryZeroDte",
    # ── VRP ──
    "VrpResponse",
    "VrpCore",
    "VrpDirectional",
    "VrpTermItem",
    "VrpGexConditioned",
    "VrpVannaConditioned",
    "VrpRegime",
    "VrpStrategyScores",
    "VrpMacro",
    # ── MaxPain ──
    "MaxPainResponse",
    "MaxPainDistance",
    "MaxPainCurveRow",
    "MaxPainOiRow",
    "MaxPainByExpirationRow",
    "MaxPainDealerAlignment",
    "MaxPainExpectedMove",
    # ── StockSummary ──
    "StockSummaryResponse",
    "StockSummaryPrice",
    "StockSummarySkew25d",
    "StockSummaryIvTermItem",
    "StockSummaryVolatility",
    "StockSummaryOptionsFlow",
    "StockSummaryInterpretation",
    "StockSummaryHedgingMove",
    "StockSummaryHedgingEstimate",
    "StockSummaryZeroDte",
    "StockSummaryTopStrike",
    "StockSummaryExposure",
    "StockSummaryMacroIndex",
    "StockSummaryVixTermLevels",
    "StockSummaryVixTermStructure",
    "StockSummaryVixFutures",
    "StockSummaryFearAndGreed",
    "StockSummaryMacro",
    # ── Narrative ──
    "NarrativeResponse",
    "Narrative",
    "NarrativeData",
    "NarrativeOiChange",
    # ── ExposureLevels ──
    "ExposureLevelsResponse",
    "ExposureLevels",
    # ── PricingGreeks ──
    "PricingGreeksResponse",
    "PricingInputs",
    "PricingFirstOrder",
    "PricingSecondOrder",
    "PricingThirdOrder",
    "PricingAdditional",
    # ── Volatility ──
    "VolatilityResponse",
    "VolatilityRealizedVol",
    "VolatilityIvRvSpreads",
    "VolatilitySkewProfile",
    "VolatilityTermStructure",
    "VolatilityIvDispersion",
    "VolatilityGexByDte",
    "VolatilityThetaByDte",
    "VolatilityPcByExpiry",
    "VolatilityPcByMoneyness",
    "VolatilityPutCallProfile",
    "VolatilityOiConcentration",
    "VolatilityHedgingScenario",
    "VolatilityLiquidity",
    # ── AdvVolatility ──
    "AdvVolatilityResponse",
    "AdvVolSviParam",
    "AdvVolForwardPrice",
    "AdvVolTotalVarianceSurface",
    "AdvVolArbitrageFlag",
    "AdvVolVarianceSwap",
    "AdvVolGreekSurface",
    "AdvVolGreeksSurfaces",
    # ── Surface ──
    "SurfaceResponse",
    # ── Per-strike Exposure (GEX/DEX/VEX/CHEX) ──
    "GexResponse",
    "GexStrikeRow",
    "DexResponse",
    "DexStrikeRow",
    "VexResponse",
    "VexStrikeRow",
    "ChexResponse",
    "ChexStrikeRow",
    # ── Live-only Quote endpoints ──
    "OptionQuoteResponse",
    "StockQuoteResponse",
]
